logging:
  level:
    hello: INFO
    org:
      springframework:
        ws: DEBUG
        data:
          mongodb: DEBUG

server:
  port: 8081

spring:
  application:
    name: Bootstrap Spring Boot
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: bustrace
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    order: 0

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://192.168.0.101:27017